### ISSUE TITLE
Add system version 0.1

### ISSUE THREAD

**Issue by TechnomageLiloi** [TechnomageLiloi/Rune#2]
# Tasks

- [x] Add composer system
- [x] Add test systems (phpUnit, Jasmine)
- [x] Add framework
- [x] Add security block
  - [x] Add password block
- [x] Add interstate block
  - [x] Add interstate database table
  - [x] Add interstate domain
  - [x] Add interstate CRUD API methods
  - [x] Add interface
